# Generated by Django 2.1.1 on 2018-11-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(blank=True, default='', max_length=255)),
                ('street_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, default='', max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.TextField(blank=True, default='', help_text='JSON Object')),
                ('type', models.CharField(blank=True, default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True)),
                ('registration_code', models.CharField(blank=True, default='', max_length=100)),
                ('domain', models.CharField(blank=True, default='', help_text='If populated, restrict email registration to this address.', max_length=512)),
                ('website', models.CharField(blank=True, default='', max_length=512)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('point_of_contact', models.CharField(blank=True, default='', max_length=512)),
                ('addresses', models.ManyToManyField(blank=True, to='accounts.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, default='', max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.TextField(blank=True, default='', help_text='JSON Object')),
                ('type', models.CharField(blank=True, default='', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TMF', 'Transgender Male to Female'), ('TFM', 'Transgender Female to Male'), ('U', 'Unknown')], default='U', help_text='Gender / Gender Identity', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname, alias, or other names used.', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', help_text='Sex', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, default='', help_text='US numbers only.', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.OrganizationIdentifier'),
        ),
        migrations.AddField(
            model_name='address',
            name='ind_identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.IndividualIdentifier'),
        ),
        migrations.AddField(
            model_name='address',
            name='org_identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.OrganizationIdentifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ind_identifiers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.IndividualIdentifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.OrganizationIdentifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='accounts.Organization'),
        ),
    ]
