# Generated by Django 2.1.2 on 2018-11-26 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20181106_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAffiliationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('can_approve_affiliation', 'Can approve affiliation'),),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Subject for identity token', max_length=64),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='value',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='point_of_contact',
        ),
        migrations.AddField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(on_delete='PROTECT', to=settings.AUTH_USER_MODEL, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationidentifier',
            name='value',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationaffiliationrequest',
            name='organization',
            field=models.ForeignKey(on_delete='PROTECT', to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='organizationaffiliationrequest',
            name='user',
            field=models.ForeignKey(on_delete='PROTECT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationaffiliationrequest',
            unique_together={('user', 'organization')},
        ),
    ]
