# Generated by Django 2.1.1 on 2018-11-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181126_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='four_digit_suffix',
            field=models.CharField(blank=True, default='', help_text='If populated, this field must contain exactly four numbers.', max_length=4),
        ),
    ]
