# Generated by Django 2.1.1 on 2018-11-26 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_four_digit_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete='PROTECT', to=settings.AUTH_USER_MODEL),
        ),
    ]
