# Generated by Django 2.1.1 on 2018-11-28 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20181126_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='gender_identity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ind_identifiers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='org_identifiers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organizations',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete='PROTECT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualidentifier',
            name='user',
            field=models.ForeignKey(null=True, on_delete='PROTECT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone_number_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='name',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='value',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete='PROTECT', related_name='organization_point_of_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationidentifier',
            name='name',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='organizationidentifier',
            name='value',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
    ]
