# Generated by Django 2.1.1 on 2018-11-28 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181128_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='org_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
