# Generated by Django 2.1.1 on 2018-12-17 13:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181128_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='US numbers only.', max_length=128),
        ),
    ]
