# Generated by Django 2.1.2 on 2018-12-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phoneverifycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ind_identifiers',
        ),
        migrations.RemoveField(
            model_name='address',
            name='org_identifiers',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='identifiers',
        ),
        migrations.AlterField(
            model_name='organization',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='organization_addresses', to='accounts.Address'),
        ),
    ]
