# Generated by Django 2.1.7 on 2019-03-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181231_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pictue',
            field=models.ImageField(default='profile-picture/None/no-img.jpg', upload_to='profile-picture/'),
        ),
    ]
