# Generated by Django 2.1.7 on 2019-03-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_pictue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictue',
            new_name='picture',
        ),
    ]
