# Generated by Django 2.1.5 on 2019-03-28 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190327_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
