# Generated by Django 2.1.5 on 2019-05-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_address_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agree_privacy_policy',
            field=models.CharField(blank=True, default='', help_text='Do you agree to the privacy policy?', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agree_tos',
            field=models.CharField(blank=True, default='', help_text='Do you agree to the terms and conditions?', max_length=3),
        ),
    ]
