# Generated by Django 2.1.5 on 2019-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190501_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agree_privacy_policy',
            field=models.CharField(blank=True, default='', help_text='Do you agree to the privacy policy?', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agree_tos',
            field=models.CharField(blank=True, default='', help_text='Do you agree to the terms and conditions?', max_length=64),
        ),
    ]
