# Generated by Django 2.1.1 on 2018-12-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='action',
            field=models.CharField(choices=[('', 'No Action (Detail Update)'), ('1-TO-2', 'Verify Identity: Change the Identity assurance Level from 1 to 2'), ('2-TO-1', 'Administrative Downgrade: Change the Identity Assurance Level (IAL) from 2 to 1 from IAL 2 to 1.')], default='', max_length=6),
        ),
    ]
