# Generated by Django 2.1.5 on 2019-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0003_auto_20190327_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
