# Generated by Django 2.1.5 on 2019-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0004_identityassuranceleveldocumentation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
