# Generated by Django 2.1.5 on 2019-03-29 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0005_identityassuranceleveldocumentation_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
